### PR TITLE
dgraph lambda helm chart 

### PR DESCRIPTION
**Pull request by darkn3rd**
This is the initial implementation of `dgraph-lambda` helm chart and version bump for `dgraph` helm chart.  

Included in this: 
* helm chart `dgraph-lambda`
  * README.md for the dgraph-lambda with steps to configure dgraph + dgraph-lambda
  * example ingress (not tested)
* helmfiles configs
  * lambda helmfile with README and further walkthrough of steps.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)

### CODE REVIEW

**Review by danielmai — CHANGES_REQUESTED** [review]
Example files like mutation.graphql, query.graphql, resolvers.js, schema.graphql, and script.yaml should all be in an examples directory so it's clear that they're examples.

> Reviewed 24 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57#-:-MPC2S9SEG1ZN0FnjvcD:b13t9u8)* status: 23 of 25 files reviewed, 10 unresolved discussions (waiting on @danielmai and @darkn3rd)

___
*[charts/dgraph-lambda/README.md, line 17 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0-8S4uuysUAwTYnQ:-MPC0-8T23WdchSrKJ5S:b30iucm) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L17)):*
> ```
> `whitelist`
> ```
Is the whitelist flag required for lambda?
___
*[charts/dgraph-lambda/README.md, line 24 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC051wCPMSrVWHAKq6:-MPC051wCPMSrVWHAKq7:bq5sok4) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L24)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 1.
> 1.
> 1.
> 1.
> ```
</details>

Use 1. 2. 3. and so on. Even though Markdown would render it properly, use the proper numbers in the source file.
___
*[charts/dgraph-lambda/README.md, line 30 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0IHq84c0HOAKZ1R0:-MPC0IHq84c0HOAKZ1R1:b-gxfoy9) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L30)):*
> ```
> the
> ```
Remove "the"
___
*[charts/dgraph-lambda/README.md, line 53 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0V3JBaDf6zP5pztl:-MPC0V3JBaDf6zP5pztm:bmy3tm2) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L53)):*
> ```
> following: following:
> ```
Remove extra "following: "
___
*[charts/dgraph-lambda/README.md, line 61 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0Z7S9fVF8P0xkN2c:-MPC0Z7S9fVF8P0xkN2d:brmxl0n) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L61)):*
> ```
> like the example below:
> ```
You can remove these words. "like the one below" already refers to what follows "below":.
___
*[charts/dgraph-lambda/README.md, line 118 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0nl387yQi1QgQ559:-MPC0nl387yQi1QgQ55A:b-vkxdx) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L118)):*
> ```
> upload load a schema:
> ```
upload a GraphQL schema to Dgraph
___
*[helmfiles/README.md, line 5 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC1kn-9UhjStNoB5Ty:-MPC1kn-9UhjStNoB5Tz:bkvsigj) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/README.md#L5)):*
> ```
> Promtial
> ```
Promtail
___
*[helmfiles/README.md, line 5 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC1mfTCI4AxytjtcmB:-MPC1mfTCI4AxytjtcmC:b-mh2yyn) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/README.md#L5)):*
> ```
> EKF
> ```
EFK
___
*[helmfiles/lambda/resolvers.js, line 1 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC2M2g3L2rKdDH7VxZ:-MPC2M2g3L2rKdDH7Vx_:b-5yukg) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/lambda/resolvers.js#L1)):*
> ```JavaScript
> /*
> ```

Do we need this file if it's in script.yaml?
___
*[helmfiles/lambda/resolvers.js, line 3 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC2HGF-ILubPohDk6E:-MPC2HGF-ILubPohDk6F:bykvw1j) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/lambda/resolvers.js#L3)):*
> ```
> Sourdce
> ```
source

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)* status: 22 of 25 files reviewed, 8 unresolved discussions (waiting on @danielmai and @darkn3rd)

___
*[helmfiles/lambda/README.md, line 81 at r2](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC4Iuj3Pb05WZXkBSZ:-MPC4Iuj3Pb05WZXkBS_:b-yr8m2y) ([raw file](https://github.com/dgraph-io/charts/blob/91b2c96dae60e68de7bfe56fd85140bb4960b20e/helmfiles/lambda/README.md#L81)):*
> ```
> curl http://localhost:8080/graphql -sH "Content-Type: application/json" -d"$(gql2json query.graphql)"
> ```
You can use the content type header `application/graphql` and then send the file as-is. You don't need `gql2json`.

**Comment by danielmai** [comment]
___
*[helmfiles/lambda/README.md, line 81 at r2](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC4Iuj3Pb05WZXkBSZ:-MPC5fre8sOzjSUMuhWC:bxeqlu9) ([raw file](https://github.com/dgraph-io/charts/blob/91b2c96dae60e68de7bfe56fd85140bb4960b20e/helmfiles/lambda/README.md#L81)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> curl http://localhost:8080/graphql -sH "Content-Type: application/json" -d"$(gql2json query.graphql)"
> ```
You can use the content type header `application/graphql` and then send the file as-is. You don't need `gql2json`.
</blockquote></details>

e.g., `curl -XPOST http://localhost:8080/graphql -sH "Content-Type: application/graphql" -T query.graphql`

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)* status: 17 of 25 files reviewed, 8 unresolved discussions (waiting on @danielmai and @darkn3rd)

___
*[charts/dgraph-lambda/README.md, line 17 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0-8S4uuysUAwTYnQ:-MPC8VAfBN_vlDiJOqZ1:bb9yj0j) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L17)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> `whitelist`
> ```
Is the whitelist flag required for lambda?
</blockquote></details>

Let follow up on this (experiment).

I was following [docs](https://dgraph.io/docs/graphql/lambda/server/) that includes it, so I thought it was needed as it was documented in the examples.
___
*[charts/dgraph-lambda/README.md, line 24 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC051wCPMSrVWHAKq6:-MPC8pyC9Y1wn3ITVVP3:b-oc84l5) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L24)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> 1.
> 1.
> 1.
> 1.
> ```
Use 1. 2. 3. and so on. Even though Markdown would render it properly, use the proper numbers in the source file.
</blockquote></details>

Sure. 

As a general guideline, I typically use _lazy numbering_, as manual numbering can lead to mistakes.  As `1. stuff` which is `<ol><li>stuff</li></ol>`, it will always be ordered correctly.  But I am mutable to this styleguide.
___
*[charts/dgraph-lambda/README.md, line 30 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0IHq84c0HOAKZ1R0:-MPCA1AE5t0QapdtDhMV:bdlohw1) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L30)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> the
> ```
Remove "the"
</blockquote></details>

This now seems strange, and Grammarly agrees, but did it.
___
*[charts/dgraph-lambda/README.md, line 53 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0V3JBaDf6zP5pztl:-MPCAHsE8g-7VIyAdaqD:b-wl18q6) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L53)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> following: following:
> ```
Remove extra "following: "
</blockquote></details>

I cannot find htis.
___
*[charts/dgraph-lambda/README.md, line 61 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0Z7S9fVF8P0xkN2c:-MPCAJzu0K_CFvZYRw3v:b-wendg6) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L61)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> like the example below:
> ```
You can remove these words. "like the one below" already refers to what follows "below":.
</blockquote></details>

I cannot find this.
___
*[helmfiles/lambda/resolvers.js, line 1 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC2M2g3L2rKdDH7VxZ:-MPCAb7e3yuXlwoQpKkl:b-83og3x) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/lambda/resolvers.js#L1)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

Do we need this file if it's in script.yaml?
</blockquote></details>

Nope.
___
*[helmfiles/lambda/resolvers.js, line 3 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC2HGF-ILubPohDk6E:-MPCAkUeE4obztkZdTvh:b1jy2ov) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/lambda/resolvers.js#L3)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Sourdce
> ```
source
</blockquote></details>

Didn't find that.

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)* status: 16 of 24 files reviewed, 8 unresolved discussions (waiting on @danielmai)

___
*[charts/dgraph-lambda/README.md, line 24 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC051wCPMSrVWHAKq6:-MPCBG8U41mjdEIbatFI:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L24)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

Sure. 

As a general guideline, I typically use _lazy numbering_, as manual numbering can lead to mistakes.  As `1. stuff` which is `<ol><li>stuff</li></ol>`, it will always be ordered correctly.  But I am mutable to this styleguide.


</blockquote></details>

Done.
___
*[charts/dgraph-lambda/README.md, line 61 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0Z7S9fVF8P0xkN2c:-MPCB9N4BTFqaQ28iSXE:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L61)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

I cannot find this.
</blockquote></details>

Done.
___
*[charts/dgraph-lambda/README.md, line 118 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0nl387yQi1QgQ559:-MPCB9c9BjwPRL0i4K_X:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L118)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> upload load a schema:
> ```
upload a GraphQL schema to Dgraph
</blockquote></details>

Done.
___
*[helmfiles/README.md, line 5 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC1mfTCI4AxytjtcmB:-MPCB3c1-ucfRJScJLk_:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/README.md#L5)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> EKF
> ```
EFK
</blockquote></details>

Done.
___
*[helmfiles/README.md, line 5 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC1kn-9UhjStNoB5Ty:-MPCB59C2cdkPP_KksBH:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/README.md#L5)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> Promtial
> ```
Promtail
</blockquote></details>

Done.
___
*[helmfiles/lambda/README.md, line 81 at r2](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC4Iuj3Pb05WZXkBSZ:-MPCB2YE2nPoaQO_wZre:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/91b2c96dae60e68de7bfe56fd85140bb4960b20e/helmfiles/lambda/README.md#L81)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

e.g., `curl -XPOST http://localhost:8080/graphql -sH "Content-Type: application/graphql" -T query.graphql`
</blockquote></details>

Done.

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)* status: 15 of 24 files reviewed, 9 unresolved discussions (waiting on @danielmai)

*[a discussion](https://reviewable.io/reviews/dgraph-io/charts/57#-MPCZVIe8xB2s_Z6wHMx:-MPCZVIe8xB2s_Z6wHMy:b-gtpdnu) (no related file):*
Updated with the recommended changes, found 2 doc/readme bugs and one helm chart bug.

---
___
*[charts/dgraph-lambda/README.md, line 17 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0-8S4uuysUAwTYnQ:-MPCZLDAC0qZPjkWQLM-:b-mxkjo4) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L17)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

Let follow up on this (experiment).

I was following [docs](https://dgraph.io/docs/graphql/lambda/server/) that includes it, so I thought it was needed as it was documented in the examples.
</blockquote></details>

Removed whitelist.
___
*[helmfiles/lambda/resolvers.js, line 1 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC2M2g3L2rKdDH7VxZ:-MPCZRzKCNoxkGB5jhsa:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/lambda/resolvers.js#L1)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

Nope.
</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)* status: all files reviewed, 1 unresolved discussion

___
*[charts/dgraph-lambda/README.md, line 53 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0V3JBaDf6zP5pztl:-MPCpeGO2UoZxJPZeD4D:bihkhem) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L53)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

I cannot find htis.
</blockquote></details>

This was in your original commit for this PR. I had already retracted this comment.
___
*[charts/dgraph-lambda/README.md, line 61 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC0Z7S9fVF8P0xkN2c:-MPCppw68Br8sb5TdPy9:bkf6xjr) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/charts/dgraph-lambda/README.md#L61)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You removed "like the one below" when I had asked you to remove "like the example below." Anyway, it still makes sense either way.
___
*[helmfiles/lambda/resolvers.js, line 3 at r1](https://reviewable.io/reviews/dgraph-io/charts/57#-MPC2HGF-ILubPohDk6E:-MPCqgkhCsBSp6UdqWPz:b-w462g0) ([raw file](https://github.com/dgraph-io/charts/blob/51891085f255b4f10028f87d70d9cb0225b968f1/helmfiles/lambda/resolvers.js#L3)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

Didn't find that.
</blockquote></details>

This was in your original commit in this PR. I had retracted this comment for your later commits.

**Review by danielmai — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57#-:-MPCqycaE2iZ04U_9SSp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/57)* status: all files reviewed, 2 unresolved discussions (waiting on @darkn3rd)

___
*[helmfiles/lambda/helmfile.yaml, line 4 at r3](https://reviewable.io/reviews/dgraph-io/charts/57#-MPCsIPp2yKb5xTqtNHu:-MPCsIPp2yKb5xTqtNHv:byxd58i) ([raw file](https://github.com/dgraph-io/charts/blob/7a71bd010c92cd49fcd57213f7e611cdc24c5e76/helmfiles/lambda/helmfile.yaml#L4)):*
> ```YAML
> 
> releases:
>   - name: dev
> ```

Would it be clearer if you called this "dgraph" and the lambda one "dgraph-lambda"? So that the helm release names clearly show that both Dgraph and Dgraph Lambda are deployed:
```
$ helmfile list
NAME         	NAMESPACE	ENABLED	LABELS
dgraph       	default  	true   	      
dgraph-lambda	default  	true   	  
```

**Pull request merged**
