### PR TITLE
added chart variable for additional flags in alpha/zero

### PR DESCRIPTION
**Pull request by juniorsnts**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/charts/28)

### CODE REVIEW

**Comment by danielmai** [comment]
Thanks for the PR, @juniorsnts. While this is useful, I wonder if this is the best way to expose the option to add additional flags. Would it be better to add a specific field per option?

**Comment by keshareenv** [comment]
@darkn3rd Is there an environment variable or parameter in config file which can be used to set logging, tracing configs like `--v=3 --trace=0.1`

**Comment by darkn3rd** [comment]
@keshareenv These can be set in the configuration file or environment variables.  All command args should have corresponding env var and configuration.

**Comment by darkn3rd** [comment]
Merged https://github.com/dgraph-io/charts/pull/51 to master.

**Pull request closed without merging**
