### PR TITLE
Add support for nameOverride and fullnameOverride

### PR DESCRIPTION
**Pull request by kovalskyi**
We've been using a customized version of this Helm chart, where we added a common `fullnameOverride` value. Now we would like to migrate to the official chart, so we require this value as well to reuse existing PVCs.

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/charts/7)

### CODE REVIEW

**Comment by lukaszlenart** [comment]
Any chance to get this merged?

**Comment by prashant-shahi** [comment]
@kovalskyi Thank you for the PR.

It looks good to be merged after addressing comments.

**Comment by lukaszlenart** [comment]
Thanks a lot! Do you automatically publish this chart?

**Comment by lukaszlenart** [comment]
Thank you :)

**Pull request merged**
