### PR TITLE
Tenacious T’Challa update

### PR DESCRIPTION
**Pull request by darkn3rd**
This PR updates dgraph helm chart for v20.11.0

* updated examples for v20.11.0 defaults, mTLS for alpha external ports, and new mTLS zero/alpha internal ports
* updated instructions for mTLS for alpha external ports, and new mTLS zero/alpha internal ports
* updated make_tls_secrets.sh script to generate certificates/keys and helm chart config for zero/alpha mTLS
* added helmfile example for mTLS

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58)

### CODE REVIEW

**Comment by danielmai** [comment]
___
*[charts/dgraph/README.md, line 240 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM8pDwE2HjW8Wuv-4V:-MPM8pDwE2HjW8Wuv-4W:b-my5egk) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L240)):*
> ```
> https://github.com/dgraph-io/charts/blob/master/charts/
> ```
You can use a relative link and GitHub will create the right link depending on what branch you're on. That way, you don't always link to master.

**Comment by danielmai** [comment]
___
*[charts/dgraph/README.md, line 353 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9bgI68Vfvq2L749_:-MPM9bgI68Vfvq2L749a:b7umpcb) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L353)):*
> ```
> kubectl port-forward $RELEASE-dgraph-zero-0 6080:6080 &
> ```
Can we remove the trailing `&`? You already said to run this in another terminal tab.

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 22 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58)* status: 20 of 28 files reviewed, 8 unresolved discussions (waiting on @darkn3rd)

___
*[charts/dgraph/README.md, line 304 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9F140wslwQs-l6po:-MPM9F140wslwQs-l6pp:b-wee1t0) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L304)):*
> ```
> now secure
> ```
now use secure
___
*[charts/dgraph/example_values/config-hcl-file.yaml, line 16 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9vXdEeMrhUqEjNmL:-MPM9vXe-LFzZaUs3Rqt:bwb1vc7) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/example_values/config-hcl-file.yaml#L16)):*
> ```
>       "postings" = "/dgraph/data/p"
>       "wal" = "/dgraph/data/w"
> ```
Why are these set to `/dgraph/data`? This isn't the typical default.
___
*[charts/dgraph/example_values/config-toml-file.yaml, line 24 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMA9sr1cOaXiBJzPFc:-MPMA9sr1cOaXiBJzPFd:b-2b1s17) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/example_values/config-toml-file.yaml#L24)):*
> ```
>  wal = '/dgraph/data/w'
> ```
Again, where did `/dgraph/data` come from? The default path is `/dgraph`.
___
*[charts/dgraph/scripts/README.md, line 14 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMB77_6SvJW2cFTdMq:-MPMB77_6SvJW2cFTdMr:bhv8ez3) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/scripts/README.md#L14)):*
> ```
> defualt
> ```
`default`
___
*[charts/dgraph/scripts/README.md, line 27 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMB9tO-AkcChWAxlKR:-MPMB9tO-AkcChWAxlKS:bt5wcg2) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/scripts/README.md#L27)):*
> ```
> examples/dgraph_tls/alpha
> ```
This should say ./dgraph_tls/alpha. The command above didn't create an examples directory.
___
*[charts/dgraph/scripts/README.md, line 27 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMBEb30Jt7-ab0QUq5:-MPMBEb30Jt7-ab0QUq6:bpk9rfr) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/scripts/README.md#L27)):*
> ```Markdown
> dgraph cert ls --dir ./dgraph_tls/alpha
> ## verify list of addresses supported
> dgraph cert ls --dir examples/dgraph_tls/alpha | awk -F: '/Hosts/{gsub(/\s+/, "", $2); print $2}' | tr , '\n'
> ```

The output here looks off. The awk command is removing the `s` characters too.

```
$ dgraph cert ls --dir ./dgraph_tls/alpha | awk -F: '/Hosts/{gsub(/\s+/, "", $2); print $2}' | tr , '\n'       

 localhot
 my-releae-dgraph-alpha-0.my-releae-dgraph-alpha-headle.defualt.vc.cluter.local
 my-releae-dgraph-alpha-1.my-releae-dgraph-alpha-headle.defualt.vc.cluter.local
 my-releae-dgraph-alpha-2.my-releae-dgraph-alpha-headle.defualt.vc.cluter.local
 ratel.example.com
 alpha.example.com
```

**Review by danielmai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 30 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58)* status: 25 of 28 files reviewed, 14 unresolved discussions (waiting on @darkn3rd)

___
*[helmfiles/mutual_tls/README.md, line 20 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMBwbF3Z8EYaD0W5C4:-MPMBwbF3Z8EYaD0W5C5:b-2xw7yb) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L20)):*
> ```
>  that can be use to the helm chart
> ```
that can be used for the helm chart.
___
*[helmfiles/mutual_tls/README.md, line 43 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMC59h570GTj4WYCtI:-MPMC59h570GTj4WYCtJ:b5web1e) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L43)):*
> ```
> If will set the configuration, and if the environment variable is not specified, it will default to `VERIFYIFGIVEN`.
> ```
This needs to be rephrased?
___
*[helmfiles/mutual_tls/README.md, line 67 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMCfUl9uU4lcvqwlwE:-MPMCfUl9uU4lcvqwlwF:b-j510fq) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L67)):*
> ```
> kubectl port-forward my-release-dgraph-alpha-0 8080:8080 &
> ```
Does this need to run in the background if it's run in a different tab?
___
*[helmfiles/mutual_tls/README.md, line 68 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMD1DBDz1X77l0CbXb:-MPMD1DBDz1X77l0CbXc:b-3ga3vi) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L68)):*
> ```
> VERIFYGIVEN
> ```
VERIFYIFGIVEN
___
*[helmfiles/mutual_tls/README.md, line 74 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMCiIHCUy21npNk3JS:-MPMCiIHCUy21npNk3JT:bfp9rvq) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L74)):*
> ```
> kubectl port-forward my-release-dgraph-alpha-0 9080:9080 &
> ```

Does this need to run in the background if it's run in a different tab?
___
*[helmfiles/mutual_tls/README.md, line 75 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMCsaC-YFf_tjggS5G:-MPMCsaC-YFf_tjggS5H:b-bltq6k) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L75)):*
> ```
> VERIFYGIVEN
> ```
`VERIFYIFGIVEN`

**Review by danielmai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58)* status: 25 of 28 files reviewed, 15 unresolved discussions (waiting on @darkn3rd)

___
*[helmfiles/mutual_tls/helmfile.yaml, line 15 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMDuO99KbCBEMpg2ZO:-MPMDuO99KbCBEMpg2ZP:b-3ga3vi) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/helmfile.yaml#L15)):*
> ```
> VERIFYGIVEN
> ```
VERIFYIFGIVEN

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58)* status: 25 of 28 files reviewed, 15 unresolved discussions (waiting on @danielmai and @darkn3rd)

___
*[charts/dgraph/README.md, line 353 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9bgI68Vfvq2L749_:-MPMF9-l5eFrBB5KNw2Z:b8ss8v4) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L353)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> kubectl port-forward $RELEASE-dgraph-zero-0 6080:6080 &
> ```
Can we remove the trailing `&`? You already said to run this in another terminal tab.
</blockquote></details>

If they do not use another terminal tab, then these instructions will not work.  Flexible to make the instructions no longer work, or organize it into separate code blocks.
___
*[charts/dgraph/example_values/config-hcl-file.yaml, line 16 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9vXdEeMrhUqEjNmL:-MPMEZFFDdTF7TWDS36l:b-46142y) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/example_values/config-hcl-file.yaml#L16)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>       "postings" = "/dgraph/data/p"
>       "wal" = "/dgraph/data/w"
> ```
Why are these set to `/dgraph/data`? This isn't the typical default.
</blockquote></details>

Showing an alternative configuration, keeps the data organized under `./data` to keep it organized with `./tls`, `./config` and so forth.

**Review by darkn3rd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58)* status: 16 of 29 files reviewed, 15 unresolved discussions (waiting on @danielmai)

___
*[charts/dgraph/README.md, line 240 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM8pDwE2HjW8Wuv-4V:-MPMYSDwCGJr8rS6BG71:b-2194z7) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L240)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> https://github.com/dgraph-io/charts/blob/master/charts/
> ```
You can use a relative link and GitHub will create the right link depending on what branch you're on. That way, you don't always link to master.
</blockquote></details>

As discussed, external sites cannot use relative links. :'(
___
*[charts/dgraph/README.md, line 304 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9F140wslwQs-l6po:-MPMYZQ2BMH0cU3uFVvQ:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L304)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> now secure
> ```
now use secure
</blockquote></details>

Done.
___
*[charts/dgraph/README.md, line 353 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPM9bgI68Vfvq2L749_:-MPMYdxz32F7R4WLY5B1:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/README.md#L353)):*
<details><summary><i>Previously, darkn3rd (Joaquin Menchaca) wrote…</i></summary><blockquote>

If they do not use another terminal tab, then these instructions will not work.  Flexible to make the instructions no longer work, or organize it into separate code blocks.
</blockquote></details>

Done.
___
*[charts/dgraph/example_values/config-toml-file.yaml, line 24 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMA9sr1cOaXiBJzPFc:-MPM_5G03nv0tVBDTU6E:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/example_values/config-toml-file.yaml#L24)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>  wal = '/dgraph/data/w'
> ```
Again, where did `/dgraph/data` come from? The default path is `/dgraph`.
</blockquote></details>

Done.
___
*[charts/dgraph/scripts/README.md, line 14 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMB77_6SvJW2cFTdMq:-MPMYjKw-WgBhFY-dd6a:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/scripts/README.md#L14)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> defualt
> ```
`default`
</blockquote></details>

Done.
___
*[charts/dgraph/scripts/README.md, line 27 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMB9tO-AkcChWAxlKR:-MPMYlwd9ywTHqyAxkU2:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/scripts/README.md#L27)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> examples/dgraph_tls/alpha
> ```
This should say ./dgraph_tls/alpha. The command above didn't create an examples directory.
</blockquote></details>

Done.
___
*[charts/dgraph/scripts/README.md, line 27 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMBEb30Jt7-ab0QUq5:-MPMYouJDprvjocyAqeq:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/charts/dgraph/scripts/README.md#L27)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

The output here looks off. The awk command is removing the `s` characters too.

```
$ dgraph cert ls --dir ./dgraph_tls/alpha | awk -F: '/Hosts/{gsub(/\s+/, "", $2); print $2}' | tr , '\n'       

 localhot
 my-releae-dgraph-alpha-0.my-releae-dgraph-alpha-headle.defualt.vc.cluter.local
 my-releae-dgraph-alpha-1.my-releae-dgraph-alpha-headle.defualt.vc.cluter.local
 my-releae-dgraph-alpha-2.my-releae-dgraph-alpha-headle.defualt.vc.cluter.local
 ratel.example.com
 alpha.example.com
```
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/helmfile.yaml, line 15 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMDuO99KbCBEMpg2ZO:-MPMYpsv4RMdU4drq9WL:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/helmfile.yaml#L15)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> VERIFYGIVEN
> ```
VERIFYIFGIVEN
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/README.md, line 20 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMBwbF3Z8EYaD0W5C4:-MPMYsd39GvmcIh6k1NS:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L20)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
>  that can be use to the helm chart
> ```
that can be used for the helm chart.
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/README.md, line 43 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMC59h570GTj4WYCtI:-MPMYuHy7_nw066wZ7BZ:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L43)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> If will set the configuration, and if the environment variable is not specified, it will default to `VERIFYIFGIVEN`.
> ```
This needs to be rephrased?
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/README.md, line 67 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMCfUl9uU4lcvqwlwE:-MPMYwt02RHnJc2OKJib:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L67)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> kubectl port-forward my-release-dgraph-alpha-0 8080:8080 &
> ```
Does this need to run in the background if it's run in a different tab?
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/README.md, line 68 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMD1DBDz1X77l0CbXb:-MPMYvwN21yMzxTDjHiu:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L68)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> VERIFYGIVEN
> ```
VERIFYIFGIVEN
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/README.md, line 74 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMCiIHCUy21npNk3JS:-MPMYy5l5C0LB6wR-KKC:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L74)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> kubectl port-forward my-release-dgraph-alpha-0 9080:9080 &
> ```

Does this need to run in the background if it's run in a different tab?
</blockquote></details>

Done.
___
*[helmfiles/mutual_tls/README.md, line 75 at r2](https://reviewable.io/reviews/dgraph-io/charts/58#-MPMCsaC-YFf_tjggS5G:-MPMZ-N63VZbHe2o8aLf:b-896fix) ([raw file](https://github.com/dgraph-io/charts/blob/bd3e453559cacd7e64a818aa6a89b347919d93dd/helmfiles/mutual_tls/README.md#L75)):*
<details><summary><i>Previously, danielmai (Daniel Mai) wrote…</i></summary><blockquote>

> ```
> VERIFYGIVEN
> ```
`VERIFYIFGIVEN`
</blockquote></details>

Done.

**Review by danielmai — APPROVED** [review]
:lgtm:

> Reviewed 3 of 30 files at r2, 9 of 10 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/charts/58#-:-MPMeSNr3qmayoznD7Vg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @darkn3rd)

**Pull request merged**
