### PR TITLE
fix affinity for alpha sts

### PR DESCRIPTION
**Pull request by david972**
- Fix alpha sts affinity hard
- Add prometheus annotation metrics

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/charts/10)

### CODE REVIEW

**Comment by david972** [comment]
Hello @prashant-shahi 
Can we consider this pull-request ?
Should I review it or change something ?

**Comment by prashant-shahi** [comment]
Hello @david972!

Thank you for the PR. Looks great to me!!

**Comment by david972** [comment]
thanks

**Pull request merged**
